[buildPlans.iosevka-motion]
family = "Iosevka Motion"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-motion.variants.design]
capital-a = "straight-motion-serifed"
capital-b = "standard-interrupted-unilateral-motion-serifed"
capital-c = "bilateral-inward-serifed"
capital-d = "standard-bilateral-motion-serifed"
capital-e = "motion-serifed"
capital-f = "motion-serifed"
capital-g = "toothed-inward-serifed-capped"
capital-h = "motion-serifed"
capital-i = "serifed"
capital-j = "descending-serifed"
capital-k = "straight-motion-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed-motion-serifed"
capital-r = "standing-motino-serifed"
capital-s = "unilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "motion-serifed-tailed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "motion-serifed"
a = "double-storey-motion-serifed"
b = "toothed-motion-serifed"
c = "bilateral-inward-serifed"
d = "toothed-motion-serifed"
e = "flat-crossbar"
f = "flat-hook-serifed"
g = "single-storey-motion-serifed-flat-hook"
h = "straight-motion-serifed"
j = "flat-hook-serifed"
k = "straight-motion-serifed"
m = "short-leg-motion-serifed-tailed"
n = "straight-motion-serifed"
p = "motion-serifed"
q = "motion-serifed-tailed"
r = "compact-top-serifed"
s = "unilateral-inward-serifed"
t = "flat-hook-short-neck2"
u = "motion-serifed"
v = "straight-motion-serifed"
w = "straight-motion-serifed"
x = "straight-motion-serifed"
y = "straight-motion-serifed"
z = "motion-serifed"
zero = "long-dotted"
one = "base-flat-top-serif"
three = "flattop"
five = "vertical-upper-left-bar"
seven = "straight-crossbar"
eight = "two-circles"
asterisk = "low"
underscore = "above-baseline"
caret = "high"
number-sign = "slanted"
ampersand = "upper-open"
at = "short"
dollar = "through-cap"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"
question = "corner"

  [buildPlans.iosevka-motion.ligations]
  inherits = "clike"
